services:
  demo-setup:
    image: alpine:3.19
    container_name: demo-arc-setup

    volumes:
      - .:/project
      - /var/run/docker.sock:/var/run/docker.sock

    working_dir: /project

    environment:
      GITHUB_PAT: ${GITHUB_PAT}
      GITHUB_CONFIG_URL: ${GITHUB_CONFIG_URL}

    entrypoint:
      - /bin/sh
      - /project/entrypoint.sh

    networks:
      - arc-demo

networks:
  arc-demo:
    name: arc-runners-demo-network