services:
  floci-aws:
    image: floci/floci:latest
    container_name: floci-aws

    ports:
      - "4566:4566"

    networks:
      - arc-demo

  demo-setup:
    image: alpine:3.19
    container_name: demo-arc-setup

    volumes:
      - .:/project
      - /var/run/docker.sock:/var/run/docker.sock

    working_dir: /project

    environment:
      GITHUB_PAT: ${GITHUB_PAT}
      DOCKER_NETWORK: arc-runners-demo-network

    entrypoint:
      - /bin/sh
      - /project/entrypoint.sh

    depends_on:
      - floci-aws

    networks:
      - arc-demo

networks:
  arc-demo:
    name: arc-runners-demo-network